Repository softwareplanet/leadboard, pull requests merged in 2018-08, with the labels that each got.

#23 exclude frontend tests run from backend
  client/config/enzyme.config.js
  client/package.json
  client/scripts/testRun.js
  client/src/App.test.js
  client/src/components/modal/AddLead.js
  client/src/index.js
  package.json
Labels: enhancement

#11 User can see leadboard after login
  .gitignore
  api/funnel/index.js
  client/package.json
  client/src/App.css
  client/src/actions/leadActions.js
  client/src/components/Dashboard/Dashboard.css
  client/src/components/Dashboard/Dashboard.js
  client/src/components/Dashboard/index.test.js
  package.json
  todo
Labels: epic: leadboard

#12 User can see all his leads on the leadboard
  api/lead/index.js
  api/lead/index.test.js
  client/src/App.js
  client/src/components/Dashboard/Dashboard.js
  client/src/components/EditLead/EditLeadHeader/EditLeadHeader.js
  client/src/components/EditLead/EditLeadHeader/EditLeadStageProgress/EditLeadStageProgress.js
  client/src/components/Lead/Lead.css
  client/src/components/Lead/Lead.js
  client/src/components/Lead/Lead.test.js
  client/src/img/profile.svg
  models/contact.js
  models/lead.js
  models/organization.js
  test/db-prepare.js
  validation/lead.js
Labels: story

#10 log in with valid credentials
  .gitignore
  api/auth/index.js
  api/authorize.js
  api/funnel/index.js
  api/index.js
  api/lead/index.js
  api/passport.js
  api/stage/index.js
  api/user/index.js
  app.js
  client/config/configuration.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/actions/authActions.js
  client/src/components/auth/Login.css
  client/src/components/auth/Login.js
  client/src/components/auth/Login.test.js
  client/src/components/auth/Registration.js
  client/src/components/common/InputGroup/InputGroup.js
  client/src/components/common/InputGroup/InputGroup.test.js
  client/src/components/common/InputGroup/readme.md
  client/src/components/common/PrivateRoute.js
  client/src/reducers/authReducer.js
  client/src/utils/setAuthToken.js
  express.js
  models/user.js
  mongoose.js
  package-lock.json
  package.json
  server.js
  validation/lead.js
  validation/login.js
  validation/stage.js
  validation/validationUtils.js
Labels: story

#55 fix #53 outline on "x" button on lead modal
  client/src/components/modal/AddLead/AddLead.css
Labels: bug

#60 Add ws config
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dictionaries/intern.xml
  .idea/jsLibraryMappings.xml
  .idea/leadboard.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: technical task

#57 56 bug close add modal on esc
  client/src/components/modal/AddLead/AddLead.js
Labels: bug

#69 Remove leadboard page scrolling
  client/src/index.css
Labels: invalid, technical task

#79 29 user can see notes for lead
  api/auth/index.test.js
  api/authorize.js
  api/lead/index.js
  api/passport.js
  client/src/assets/note-icon.svg
  client/src/index.css
  client/src/modules/auth/Login/Login.css
  client/src/modules/auth/types.js
  client/src/modules/common/InfoWraper/InfoItemWrapper.css
  client/src/modules/common/InfoWraper/InfoItemWrapper.js
  client/src/modules/lead/EditLead/EditLead.js
  client/src/modules/lead/EditLead/EditLeadContent/EditLeadContent.js
  client/src/modules/lead/EditLead/Notes/Note/Note.css
  client/src/modules/lead/EditLead/Notes/Note/Note.js
  client/src/modules/lead/EditLead/Notes/Notes.css
  client/src/modules/lead/EditLead/Notes/Notes.js
  client/src/utils/formatDate.js
  client/src/utils/isBlank.js
  mongoose.js
  validation/validationUtils.js
Labels: story

#122 75 filter panel for lead information
  client/src/modules/common/InfoWraper/InfoItemWrapper.js
  client/src/modules/lead/EditLead/EditLeadContent/EditLeadContent.js
  client/src/modules/lead/EditLead/EditLeadContent/EditLeadHistory/EditLeadHistory.js
  client/src/modules/lead/EditLead/EditLeadSidebar/EditLeadSidebar.js
  client/src/modules/lead/EditLead/Notes/Note/Note.css
  client/src/modules/lead/EditLead/Notes/Notes.css
  client/src/modules/lead/EditLead/Notes/Notes.js
Labels: epic: editLead, story

#133 131 wrong lead name bug
  client/src/modules/lead/AddLead/AddLead.js
Labels: bug

#149 fix creating existing organization in add lead modal
  client/src/modules/lead/AddLead/AddLead.js
Labels: bug
